/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import Clases.Mail;
import Clases.Panel_Fondo;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author UNI
 */
public class Gui_Principal extends javax.swing.JFrame {

    public Gui_Principal() {

        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/Images/dep_medico.png")).getImage());
        } catch (NullPointerException ex) {
        }

        initComponents();
        //    this.setResizable(false);
        EnviarCorreoCita();
        Especialidad.setVisible(false);
        Medico.setVisible(false);
        Paciente.setVisible(false);
        Cita.setVisible(false);
        Consulta.setVisible(false);
        Usuario.setVisible(false);
        Reporte.setVisible(false);

    }

    static int ID_Usuario;

    static void setID_Usuario(int ID_Usuario) {
        Gui_Principal.ID_Usuario = ID_Usuario;
    }

    //Metodo enviar Correo
    
    ResultSet resultado;
    
    public void EnviarCorreoCita() {
        String[] Datos = new String[3];
        Calendar hoy = Calendar.getInstance();
        hoy.add(Calendar.DATE, +1);
        int mes;
        if ((hoy.get(Calendar.MONTH) + 1) == 12) {
            mes = 1;
        } else {
            mes = hoy.get(Calendar.MONTH) + 1;
        }
        String fecha1 = Integer.toString(hoy.get(Calendar.YEAR)) + "-" + Integer.toString(mes) + "-" + Integer.toString(hoy.get(Calendar.DATE));
        System.out.println(fecha1);
        try {
            resultado = Conexion.consulta("Select distinct Fecha_Cita,Hora_Cita, Mail "
                    + " from cita, paciente "
                    + " where Fecha_Cita = '"+fecha1+"' and cita.Id_Paciente = paciente.Id_Paciente");
            
            //System.out.println(resultado.next());
            while (resultado.next()) {
                //System.out.println(resultado);
                Datos[0] = String.valueOf(resultado.getString(1));
                Datos[1] = String.valueOf(resultado.getString(2));
                Datos[2] = String.valueOf(resultado.getString(3));
                
                Mail.mailAEnviar = Datos[2];
                Mail.Horario = (Datos[0] + " " + Datos[1]);
                
                System.out.println(Mail.mailAEnviar);
                
                new Thread(new Mail()).start();
                
                //Mail.mandarCorreo(Datos[2], Datos[0] + " " + Datos[1] );
            }
            
           

        } catch (SQLException ex) {
            Logger.getLogger(Gui_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public void Iniciar(String Rol) {

        if ("Medico".equals(Rol)) {
            Consulta.setVisible(true);
            Paciente.setVisible(true);
            AgregarPaciente.setVisible(false);
            VerConsulta.setVisible(false);
        }

        if ("Recepcionista".equals(Rol)) {
            Paciente.setVisible(true);
            Cita.setVisible(true);
            Reporte.setVisible(true);
        }

        if ("Admin".equals(Rol)) {
            Especialidad.setVisible(true);
            Medico.setVisible(true);
            Paciente.setVisible(true);
            Cita.setVisible(true);
            Consulta.setVisible(true);
            Usuario.setVisible(true);
            Reporte.setVisible(true);
        }

        this.setVisible(true);
        this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Paciente = new javax.swing.JMenu();
        AgregarPaciente = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        Especialidad = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        Medico = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        VerMedico = new javax.swing.JMenuItem();
        Cita = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        Consulta = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        VerConsulta = new javax.swing.JMenuItem();
        Usuario = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        Reporte = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VENTANA PRINCIPAL\n");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setName("jfPrincipal\n"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        DesktopPane = new Panel_Fondo();
        DesktopPane.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        DesktopPane.setMaximumSize(new java.awt.Dimension(800, 600));
        getContentPane().add(DesktopPane, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setInheritsPopupMenu(true);

        Paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paciente.png"))); // NOI18N
        Paciente.setText("Paciente");
        Paciente.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        AgregarPaciente.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        AgregarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        AgregarPaciente.setText("Añadir");
        AgregarPaciente.setIconTextGap(2);
        AgregarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPacienteActionPerformed(evt);
            }
        });
        Paciente.add(AgregarPaciente);

        jMenuItem13.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver.png"))); // NOI18N
        jMenuItem13.setText("Consultar");
        jMenuItem13.setBorder(null);
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        Paciente.add(jMenuItem13);

        jMenuBar1.add(Paciente);

        Especialidad.setBackground(new java.awt.Color(0, 153, 153));
        Especialidad.setForeground(new java.awt.Color(0, 204, 204));
        Especialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Especialidad.png"))); // NOI18N
        Especialidad.setText("Especialidad");
        Especialidad.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        jMenuItem2.setText("Añadir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Especialidad.add(jMenuItem2);

        jMenuItem11.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver.png"))); // NOI18N
        jMenuItem11.setText("Consultar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Especialidad.add(jMenuItem11);

        jMenuBar1.add(Especialidad);

        Medico.setForeground(new java.awt.Color(0, 102, 0));
        Medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/medico.png"))); // NOI18N
        Medico.setText("Medico");
        Medico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        jMenuItem1.setText("Añadir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Medico.add(jMenuItem1);

        VerMedico.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        VerMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver.png"))); // NOI18N
        VerMedico.setText("Consultar");
        VerMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerMedicoActionPerformed(evt);
            }
        });
        Medico.add(VerMedico);

        jMenuBar1.add(Medico);

        Cita.setForeground(new java.awt.Color(0, 0, 153));
        Cita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/citas.png"))); // NOI18N
        Cita.setText("Agendar Citas");
        Cita.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Cita.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jMenuItem4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        jMenuItem4.setText("Añadir ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Cita.add(jMenuItem4);

        jMenuItem16.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver.png"))); // NOI18N
        jMenuItem16.setText("Consultar");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        Cita.add(jMenuItem16);

        jMenuBar1.add(Cita);

        Consulta.setForeground(new java.awt.Color(0, 102, 102));
        Consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/atencionMedica.png"))); // NOI18N
        Consulta.setText("Atención Médica");
        Consulta.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        jMenuItem5.setText("Añadir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Consulta.add(jMenuItem5);

        VerConsulta.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        VerConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver.png"))); // NOI18N
        VerConsulta.setText("Consultar");
        VerConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerConsultaActionPerformed(evt);
            }
        });
        Consulta.add(VerConsulta);

        jMenuBar1.add(Consulta);

        Usuario.setForeground(new java.awt.Color(153, 0, 51));
        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Usuarios.png"))); // NOI18N
        Usuario.setText("Usuarios\n");
        Usuario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        jMenuItem10.setText("Añadir");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Usuario.add(jMenuItem10);

        jMenuItem14.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver.png"))); // NOI18N
        jMenuItem14.setText("Consultar");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        Usuario.add(jMenuItem14);

        jMenuBar1.add(Usuario);

        Reporte.setForeground(new java.awt.Color(204, 0, 0));
        Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reporte.png"))); // NOI18N
        Reporte.setText("REPORTES");
        Reporte.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minireporte.png"))); // NOI18N
        jMenuItem8.setText("Reporte por Médico");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Reporte.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minireporte.png"))); // NOI18N
        jMenuItem9.setText("Reporte General");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Reporte.add(jMenuItem9);

        jMenuBar1.add(Reporte);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Gui_AñadirMedico AM = new Gui_AñadirMedico();
        this.DesktopPane.add(AM);
        centerJIF(AM);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Gui_AgregarEspecialidad AE = new Gui_AgregarEspecialidad();
        this.DesktopPane.add(AE);
        centerJIF(AE);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Gui_AgregarCita AC = new Gui_AgregarCita();
        this.DesktopPane.add(AC);
        centerJIF(AC);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Gui_AgreAtencionMedica ACC = new Gui_AgreAtencionMedica();
        this.DesktopPane.add(ACC);
        centerJIF(ACC);    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Gui_SeleccionarMedico SM = new Gui_SeleccionarMedico(null, false);
        SM.setOpcion(1);
        SM.setVisible(true);
        SM.toFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        ModoReporte MR = new ModoReporte(null, false);
        MR.setOpcion(0);
        MR.setVisible(true);
        MR.toFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Gui_AñadirUsuario AU = new Gui_AñadirUsuario(this, true);
        AU.setVisible(true);
        AU.toFront();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Gui_VerEspecialidad VE = new Gui_VerEspecialidad();
        this.DesktopPane.add(VE);
        centerJIF(VE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void VerMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerMedicoActionPerformed
        Gui_VerMedico VM = new Gui_VerMedico();
        this.DesktopPane.add(VM);
        centerJIF(VM);     // TODO add your handling code here:
    }//GEN-LAST:event_VerMedicoActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Gui_VerPaciente VP = new Gui_VerPaciente();
        this.DesktopPane.add(VP);
        centerJIF(VP);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        Gui_VerUsuario VU = new Gui_VerUsuario();
        this.DesktopPane.add(VU);
        centerJIF(VU);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        Gui_VerCita VC = new Gui_VerCita();
        this.DesktopPane.add(VC);
        centerJIF(VC);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void VerConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerConsultaActionPerformed
        Gui_VerAtencionMedica VCC = new Gui_VerAtencionMedica();
        this.DesktopPane.add(VCC);
        centerJIF(VCC);  // TODO add your handling code here:
    }//GEN-LAST:event_VerConsultaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int opcion = JOptionPane.showConfirmDialog(this, "Seguro que desea salir del Sistema?", "Cerrar sesion", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            Gui_Login IS = new Gui_Login(null, false);
            IS.setVisible(false);
            this.dispose();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void AgregarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPacienteActionPerformed
        Gui_AgregarPaciente AP = new Gui_AgregarPaciente();
        this.DesktopPane.add(AP);
        centerJIF(AP);   // TODO add your handling code here:
    }//GEN-LAST:event_AgregarPacienteActionPerformed

    public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = DesktopPane.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Principal().setVisible(true);
                Gui_Principal app = new Gui_Principal();
                app.initComponents();
                app.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarPaciente;
    private javax.swing.JMenu Cita;
    private javax.swing.JMenu Consulta;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu Especialidad;
    private javax.swing.JMenu Medico;
    private javax.swing.JMenu Paciente;
    private javax.swing.JMenu Reporte;
    private javax.swing.JMenu Usuario;
    private javax.swing.JMenuItem VerConsulta;
    private javax.swing.JMenuItem VerMedico;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
