/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Cita;
import Clases.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class Gui_VerCita extends javax.swing.JInternalFrame {

    public Gui_VerCita() {
        initComponents();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbBusc = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("LISTA DE CITAS AGENDADAS");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1439253074_power_off.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, 40));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salir.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Buscar Citas Médicas por:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 20));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 370, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 669, 257));

        cmbBusc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbBusc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paciente", "Medico" }));
        jPanel1.add(cmbBusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 100, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("CITAS AGENDADAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 210, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/citas.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 705, 510);
    }// </editor-fold>//GEN-END:initComponents

    public void ActDes() {

        int Fila = jTable1.getSelectedRow();
        int Col = 6;

        //   System.out.println("Fila "+Fila);
        if (Fila >= 0) {

            int ID = Integer.parseInt(model.getValueAt(Fila, 0).toString());
            String Estado = model.getValueAt(Fila, Col).toString();

            if (Estado.equalsIgnoreCase("Pendiente")) {
                Cita.Cancelar_Cita(ID); //Des  
            } else {

                if (Estado.equalsIgnoreCase("Atendida")) {
                    JOptionPane.showMessageDialog(this, "Ya se ha atendido esta cita",
                            "Atendida", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Ya ha cancelado esta cita anteriormente",
                            "Cancelada", JOptionPane.ERROR_MESSAGE);
                }
            }

            CargarDatos();

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar la cita a cancelar",
                    "Seleccione", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ActDes();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public void CargarDatos() {

        model.setRowCount(0);

        String[] Header = {"No.", "Medico", "Fecha", "Dia", "Hora", "Paciente", "Estado"};
        model.setColumnIdentifiers(Header);

        String[] Datos = new String[7];

        try {

            resultado = Conexion.consulta("select ID_Cita,m.Nombres,m.Apellidos,Fecha_Cita,Dia_Cita,Hora_Cita,p.Nombres,p.Apellidos,c.Estado from "
                    + "medico m, paciente p, cita c "
                    + "where c.ID_Medico =  m.ID_Medico and c.ID_Paciente = p.ID_Paciente");

            while (resultado.next()) {
                Datos[0] = String.valueOf(resultado.getInt(1));
                String Medico = "Dr. " + resultado.getString(2).trim() + " " + resultado.getString(3).trim();
                Datos[1] = Medico;
                SimpleDateFormat SDF = new SimpleDateFormat("dd-MMM-yyyy");
                Date Fecha = resultado.getDate(4);
                Datos[2] = SDF.format(Fecha);
                Datos[3] = resultado.getString(5);
                Datos[4] = resultado.getString(6);
                String Paciente = resultado.getString(7).trim() + " " + resultado.getString(8).trim();
                Datos[5] = Paciente;
                Datos[6] = resultado.getString(9);

                model.addRow(Datos);
            }

        } catch (SQLException ex) {

        }

        jTable1.setModel(model);
    }

    ResultSet resultado;

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        CargarDatos();

// TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    public void Buscar() {

        String Buscar = txtBuscar.getText();

        model.setRowCount(0);

        String[] Header = {"No.", "Medico", "Fecha", "Dia", "Hora", "Paciente", "Estado"};
        model.setColumnIdentifiers(Header);

        String[] Datos = new String[7];

        try {

            if (cmbBusc.getSelectedIndex() == 0) {
                resultado = Conexion.consulta("select ID_Cita,m.Nombres,m.Apellidos,Fecha_Cita,Dia_Cita,Hora_Cita,p.Nombres,p.Apellidos,c.Estado from medico m, paciente p, cita c where c.ID_Medico = m.ID_Medico and c.ID_Paciente = p.ID_Paciente and p.Nombres like '%" + Buscar + "%' "
                        + "or p.Apellidos like '%" + Buscar + "%'");
            }

            if (cmbBusc.getSelectedIndex() == 1) {
                resultado = Conexion.consulta("select ID_Cita,m.Nombres,m.Apellidos,Fecha_Cita,Dia_Cita,Hora_Cita,p.Nombres,p.Apellidos,c.Estado from medico m, paciente p, cita c where c.ID_Medico = m.ID_Medico and c.ID_Paciente = p.ID_Paciente and m.Nombres like '%" + Buscar + "%' "
                        + "or m.Apellidos like '%" + Buscar + "%'");
            }

            while (resultado.next()) {
                Datos[0] = String.valueOf(resultado.getInt(1));
                String Medico = "Dr. " + resultado.getString(2).trim() + " " + resultado.getString(3).trim();
                Datos[1] = Medico;
                SimpleDateFormat SDF = new SimpleDateFormat("dd-MMM-yyyy");
                Date Fecha = resultado.getDate(4);
                Datos[2] = SDF.format(Fecha);
                Datos[3] = resultado.getString(5);
                Datos[4] = resultado.getString(6);
                String Paciente = resultado.getString(7).trim() + " " + resultado.getString(8).trim();
                Datos[5] = Paciente;
                Datos[6] = resultado.getString(9);

                model.addRow(Datos);
            }

        } catch (SQLException ex) {

        }

        jTable1.setModel(model);

    }

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        Buscar();        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    DefaultTableModel model = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {

            return false;
        }

    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbBusc;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
